"""Sync config/search-profile.yaml into n8n/weekly-job-scrape.json.

The n8n workflow embeds a copy of the search parameters (Apify request body),
the exclude patterns (Code-node filter) and the Drive folder id. This script
regenerates those embedded values from the YAML so the weekly scrape always
matches what the UI shows.

Usage:
    python3 pipeline/config_to_n8n.py            # dry run: report what would change
    python3 pipeline/config_to_n8n.py --write    # rewrite n8n/weekly-job-scrape.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "config" / "search-profile.yaml"
WORKFLOW_PATH = ROOT / "n8n" / "weekly-job-scrape.json"


def load_config() -> dict:
    import yaml

    with open(CONFIG_PATH, encoding="utf-8") as f:
        return yaml.safe_load(f)


def build_apify_body(cfg: dict) -> str:
    search = cfg.get("search", {})
    body = {
        "titles": search.get("titles", []),
        "location": search.get("location", ""),
        "workModes": search.get("work_modes", []),
        "maxAgeDays": (cfg.get("filters") or {}).get("max_age_days", 14),
    }
    return "={{ JSON.stringify(" + json.dumps(body, ensure_ascii=False, indent=2) + ") }}"


def build_filter_code(cfg: dict) -> str:
    filters = cfg.get("filters", {}) or {}
    # JSON-encoding each pattern list gives valid JS array literals.
    company = json.dumps(filters.get("exclude_company_patterns", []), ensure_ascii=False)
    title = json.dumps(filters.get("exclude_title_patterns", []), ensure_ascii=False)
    return (
        "// Light in-workflow filter mirroring pipeline/filter_jobs.py.\n"
        "// Regenerated by pipeline/config_to_n8n.py --write — do not edit by hand.\n"
        f"const EXCLUDE_COMPANY = {company};\n"
        f"const EXCLUDE_TITLE = {title};\n"
        "const seen = new Set();\n"
        "return items.filter((item) => {\n"
        "  const j = item.json;\n"
        "  const id = String(j.id || j.jobId || j.url || Math.random());\n"
        "  if (seen.has(id)) return false;\n"
        "  seen.add(id);\n"
        "  const company = String(j.companyName || j.company || \"\").toLowerCase();\n"
        "  const title = String(j.title || \"\").toLowerCase();\n"
        "  if (EXCLUDE_COMPANY.some((p) => new RegExp(p, \"i\").test(company))) return false;\n"
        "  if (EXCLUDE_TITLE.some((p) => new RegExp(p, \"i\").test(title))) return false;\n"
        "  return true;\n"
        "});"
    )


def sync(write: bool) -> int:
    cfg = load_config()
    workflow = json.loads(WORKFLOW_PATH.read_text(encoding="utf-8"))

    changes: list[str] = []
    for node in workflow.get("nodes", []):
        if node.get("id") == "apify-scrape":
            new_body = build_apify_body(cfg)
            if node["parameters"].get("jsonBody") != new_body:
                node["parameters"]["jsonBody"] = new_body
                changes.append("apify-scrape: search titles/location/work modes/max age")
        elif node.get("id") == "filter-code":
            new_code = build_filter_code(cfg)
            if node["parameters"].get("jsCode") != new_code:
                node["parameters"]["jsCode"] = new_code
                changes.append("filter-code: exclude patterns")
        elif node.get("id") == "drive-upload":
            folder = (cfg.get("output") or {}).get("drive_folder_id", "")
            if node["parameters"]["folderId"].get("value") != folder:
                node["parameters"]["folderId"]["value"] = folder
                changes.append("drive-upload: folder id")

    if not changes:
        print("n8n workflow already in sync with config/search-profile.yaml")
        return 0
    for c in changes:
        print(("updated " if write else "would update ") + c)
    if write:
        WORKFLOW_PATH.write_text(
            json.dumps(workflow, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        print(f"wrote {WORKFLOW_PATH.relative_to(ROOT)}")
    else:
        print("dry run — re-run with --write to apply")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="apply changes to the workflow file")
    sys.exit(sync(ap.parse_args().write))
